// Copyright 2025 Artiom Khachaturian
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#pragma once // TypeDefs.h
#include <websocketpp/common/asio.hpp>
#include <websocketpp/common/asio_ssl.hpp>
#include <websocketpp/common/system_error.hpp>

namespace Tpp
{

/**
 * @brief Type alias for the Asio I/O service used by WebSocket++.
 *
 * Represents the I/O service class from the Asio library, which manages
 * asynchronous input/output operations for the WebSocket connections.
 */
using IOSrv = websocketpp::lib::asio::io_service;

/**
 * @brief Type alias for the Asio SSL context used by WebSocket++.
 *
 * Represents the SSL/TLS context class from the Asio library, which manages
 * SSL/TLS settings and parameters for secure WebSocket connections.
 */
using SSLCtx = websocketpp::lib::asio::ssl::context;

/**
 * @brief Type alias for system errors used by WebSocket++.
 *
 * Represents the `system_error` class from the WebSocket++ library,
 * used to handle and encapsulate system-level errors, such as those
 * generated by Asio operations.
 */
using SysError = websocketpp::lib::system_error;

} // namespace Tpp
